name: Build Action

on:
  workflow_call:
    inputs:
      # registry:
      #   required: true
      #   type: string
      image_name:
        required: true
        type: string
      tag:
        required: true
        type: string
    secrets:
      GAR_JSON_KEY:
        required: true
      DOCKER_REGISTRY:
        required: true

# env:
#   REGISTRY: ghcr.io
#   IMAGE_NAME: ${{ github.repository }}

jobs:
  build_docker:
    name: Build docker image and push to GAR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      # - name: Login to Github Packages
      #   uses: docker/login-action@v1
      #   with:
      #     registry: ${{ secrets.DOCKER_REGISTRY }}
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Google Artifact Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: _json_key
          password: ${{ secrets.GAR_JSON_KEY }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_REGISTRY }}/${{ inputs.image_name }}:${{ inputs.tag }}
            ${{ secrets.DOCKER_REGISTRY }}/${{ inputs.image_name }}:latest

      # - name: Image digest
      #   run: echo ${{ steps.docker_build.outputs.digest }}
