name: Build Action

on:
  workflow_call:

jobs:
  build_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        run: |
          echo "Ref Name: ${{ github.ref_name }}"
      # - uses: nelonoel/branch-name@v1.0.1
      # - uses: google-github-actions/setup-gcloud@master
      # - uses: RafikFarhad/push-to-gcr-github-action@v4
      #   with:
      #     gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
      #     registry: gcr.io
      #     project_id: expapp-349719
      #     image_name: expapp
      #     image_tag: latest,${{ BRANCH_NAME }}