name: Build Action

on:
  workflow_call:

env:
  REGISTRY: us-docker.pkg.dev/expapp-pulumi/expapp
  IMAGE_NAME: expapp
  # REGISTRY: ghcr.io
  # IMAGE_NAME: ${{ github.repository }}

jobs:
  build_docker:
    name: Build docker image and push to GAR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - id: slugify
        uses: eltimn/slugify-action@v1.5

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      # - name: Login to Github Packages
      #   uses: docker/login-action@v1
      #   with:
      #     registry: ${{ env.REGISTRY }}
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Google Artifact Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: _json_key
          password: ${{ secrets.GAR_JSON_KEY }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.slugify.outputs.branch }}

      # - name: Image digest
      #   run: echo ${{ steps.docker_build.outputs.digest }}
