name: Deploy to Review

on:
  workflow_dispatch:
    # inputs:
    #   environment:
    #     description: 'Environment (review|production)'
  workflow_call:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy:
    permissions:
      deployments: write
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      # - uses: rlespinasse/github-slug-action@3.1.0

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Echo meta outputs
        run: |
          echo "Tags: ${{ steps.meta.outputs.tags }}"

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - run: npm install
        working-directory: ./pulumi

      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: review
          work-dir: ./pulumi
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      # - id: 'auth'
      #   uses: 'google-github-actions/auth@v0'
      #   with:
      #     # workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
      #     service_account: 'my-service-account@my-project.iam.gserviceaccount.com'

      # - id: 'deploy'
      #   uses: 'google-github-actions/deploy-cloudrun@v0'
      #   with:
      #     service: 'hello-cloud-run'
      #     image: 'gcr.io/cloudrun/hello'

      # - name: 'Use output'
      #   run: 'curl "${{ steps.deploy.outputs.url }}"'


      # - name: Set domain
      #   id: set-domain
      #   run: |
      #     echo "::set-output name=domain::${{ env.GITHUB_HEAD_REF_SLUG_URL }}.my-app.com"

      # - name: start deployment
      #   uses: bobheadxi/deployments@v1
      #   id: deployment
      #   with:
      #     step: start
      #     token: ${{ github.token }}
      #     env: review
      #     payload: >-
      #       {
      #         "action": "${{ github.event.action }}",
      #         "label": "${{ env.GITHUB_HEAD_REF_SLUG_URL }}"
      #       }

      - name: Echo inputs
        run: |
          echo "Ref Name: ${{ github.ref_name }}"
          echo "Environment: ${{ github.event.inputs.environment }}"

      # - name: update deployment status
      #   uses: bobheadxi/deployments@v1
      #   if: always()
      #   with:
      #     step: finish
      #     token: ${{ github.token }}
      #     status: ${{ job.status }}
      #     env: ${{ steps.deployment.outputs.env }}
      #     deployment_id: ${{ steps.deployment.outputs.deployment_id }}
      #     env_url: https://${{ steps.set-domain.outputs.domain }}
