name: Deploy to Review

on:
  workflow_dispatch:
  workflow_call:

# env:
#   REGISTRY: ghcr.io
#   IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy:
    permissions:
      # deployments: write
      contents: 'read'
      # id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: 'Authenticate to Google Cloud'
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - run: npm install
        working-directory: ./pulumi

      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: staging
          work-dir: ./pulumi
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      # - id: 'deploy'
      #   uses: 'google-github-actions/deploy-cloudrun@v0'
      #   with:
      #     service: 'hello-cloud-run'
      #     image: 'gcr.io/cloudrun/hello'

      # - name: Set domain
      #   id: set-domain
      #   run: |
      #     echo "::set-output name=domain::${{ env.GITHUB_HEAD_REF_SLUG_URL }}.my-app.com"

      # - name: start deployment
      #   uses: bobheadxi/deployments@v1
      #   id: deployment
      #   with:
      #     step: start
      #     token: ${{ github.token }}
      #     env: review
      #     payload: >-
      #       {
      #         "action": "${{ github.event.action }}",
      #         "label": "${{ env.GITHUB_HEAD_REF_SLUG_URL }}"
      #       }

      # - name: Echo inputs
      #   run: |
      #     echo "Ref Name: ${{ github.ref_name }}"
      #     echo "Environment: ${{ github.event.inputs.environment }}"

      # - name: update deployment status
      #   uses: bobheadxi/deployments@v1
      #   if: always()
      #   with:
      #     step: finish
      #     token: ${{ github.token }}
      #     status: ${{ job.status }}
      #     env: ${{ steps.deployment.outputs.env }}
      #     deployment_id: ${{ steps.deployment.outputs.deployment_id }}
      #     env_url: https://${{ steps.set-domain.outputs.domain }}
