name: PR Closed

on:
  pull_request:
    types: [closed]

env:
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

jobs:
  destroy:
    name: Destroy Pulumi Stack and Resources
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - id: slugify
        uses: eltimn/slugify-action@v1.5

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - run: npm install
        working-directory: ./pulumi

      - uses: pulumi/actions@v3
        with:
          command: destroy
          stack-name: "review-${{ steps.slugify.outputs.branch }}"
          work-dir: ./pulumi

      - run: pulumi stack rm "review-${{ steps.slugify.outputs.branch }}" --yes
        working-directory: ./pulumi

      # - name: Remove stack
      #   run: node remove-stack.js
      #   working-directory: ./pulumi/scripts
      #   env:
      #     PR_STACK_NAME: "review-${{ steps.slugify.outputs.branch }}"
      #     PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
