name: PR Closed

on:
  pull_request:
    types: [closed]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  destroy:
    name: Destroy Pulumi Stack and Resources
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment: review
    steps:
      - uses: actions/checkout@v2

      - id: slugify
        uses: eltimn/slugify-action@v1.5

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: 'Authenticate to Google Cloud'
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - run: npm install
        working-directory: ./pulumi

      - uses: pulumi/actions@v3
        with:
          command: destroy
          stack-name: "review-${{ steps.slugify.outputs.branch }}"
          work-dir: ./pulumi
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - run: pulumi stack rm "review-${{ steps.slugify.outputs.branch }}" --yes
        working-directory: ./pulumi
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

  cleanup:
    name: Cleanup docker images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - id: slugify
        uses: eltimn/slugify-action@v1.5

      # - name: Set up Docker Buildx
      #   id: buildx
      #   uses: docker/setup-buildx-action@v1

      # - name: Login to Github Packages
      #   uses: docker/login-action@v1
      #   with:
      #     registry: ${{ env.REGISTRY }}
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      - run: echo "env.IMAGE_NAME - ${{ env.IMAGE_NAME }}"

      # - name: Remove docker images
      #   run: docker image rm ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.slugify.outputs.branch }}

      - name: Delete image
        uses: bots-house/ghcr-delete-image-action@v1.0.0
        with:
          owner: ${{ github.repository_owner }}
          name: ${{ github.repository.split('/')[1] }}
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.slugify.outputs.branch }}
