name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/test.yml

  build:
    uses: ./.github/workflows/build.yml

  stack_exists:
    runs-on: ubuntu-latest
    environment: review
    steps:
      - uses: actions/checkout@v2

      - id: slugify
        uses: eltimn/slugify-action@v1.5

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - run: npm install
        working-directory: ./pulumi

      - name: Install pulumi
        uses: pulumi/setup-pulumi@v2
        with:
          pulumi-version: ^3.0.0
      - name: Check stack exists
        run: node stack-exists.js
        working-directory: ./pulumi/scripts
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

  # preview:
  #   name: Preview staging
  #   needs: build
  #   runs-on: ubuntu-latest
  #   environment: staging
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: 16

  #     - name: 'Authenticate to Google Cloud'
  #       uses: google-github-actions/auth@v0
  #       with:
  #         credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

  #     - run: npm install
  #       working-directory: ./pulumi

  #     - uses: pulumi/actions@v3
  #       with:
  #         command: preview
  #         stack-name: staging
  #         work-dir: ./pulumi
  #       env:
  #         PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
