name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/test.yml

  build:
    uses: ./.github/workflows/build.yml
    needs: test

  preview:
    name: Preview
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          # project_id: expapp-pulumi
          # service_account: 'github-actions@expapp-pulumi.iam.gserviceaccount.com'
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
      - run: npm install
        working-directory: ./pulumi
      - uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: staging
          work-dir: ./pulumi
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

  # deploy-review:
  #   uses: ./.github/workflows/deploy-review.yml
