name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/test.yml
  # pr:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
