name: Push to main

on:
  push:
    branches: ['main']

jobs:
  test:
    uses: ./.github/workflows/test.yml

  build:
    uses: ./.github/workflows/build.yml

  deploy_staging:
    uses: ./.github/workflows/deploy-staging.yml
    needs: build
